#lang racket

(define (make-account balance init-pw)
  (define count 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pw m)
    (if (eq? pw init-pw)
        (begin (set! count 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request: MAKE-ACCOUNT"
                                  m))))
        (lambda (x)
          (begin (displayln "Incorrect password")
                 (set! count (+ count 1))
                 (if (= count 7)
                     call-the-cops
                     (void))))))
  dispatch)
